"""Training tombol suit -> TFLite float32 -> header untuk ESP32.

Jalankan: python training/train.py --out . --epochs 180
Data ini menggambarkan tiga tombol pilihan, bukan dataset sensor jari manusia.
"""
import os
os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")
os.environ.setdefault("TF_NUM_INTEROP_THREADS", "1")
os.environ.setdefault("TF_NUM_INTRAOP_THREADS", "1")
os.environ.setdefault("TF_ENABLE_ONEDNN_OPTS", "0")

import argparse
import csv
import hashlib
import json
from pathlib import Path
import numpy as np
import tensorflow as tf

LABELS = ["BATU", "GUNTING", "KERTAS", "TIDAK_VALID"]
# Encoding internal yang dipakai firmware dan model yang dibundel.
# Di rangkaian, pemain cukup menekan satu tombol berlabel BATU/GUNTING/KERTAS.
BUTTON_FEATURES = np.array([[0, 0, 0], [1, 1, 0], [1, 1, 1]], dtype=np.float32)
SEED = 42


def label_for(x):
    """Mengenali encoding tombol; kombinasi lain dianggap ambigu."""
    low, high = x <= 0.30, x >= 0.70
    if low.all():
        return 0
    if high[0] and high[1] and low[2]:
        return 1
    if high.all():
        return 2
    return 3


def make_dataset(root):
    rng = np.random.default_rng(SEED)
    all_rows = []
    # Split dibuat terpisah; jumlah seimbang untuk empat kelas.
    for split, per_class in [("train", 1000), ("validation", 250), ("test", 250)]:
        for label in range(4):
            made = 0
            while made < per_class:
                if label < 3:
                    bits = BUTTON_FEATURES[label]
                    x = np.array([rng.uniform(.70, 1) if b else rng.uniform(0, .30)
                                  for b in bits])
                else:
                    x = rng.uniform(0, 1, size=3)
                # Simpan fitur internal; label dihitung ulang setelah pembulatan.
                raw = np.rint(x * 4095).astype(int)
                if label_for(raw / 4095.0) != label:
                    continue
                all_rows.append([*raw.tolist(), label, LABELS[label], split])
                made += 1
    rng.shuffle(all_rows)
    path = root / "data" / "dataset_sintetis.csv"
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["input_1", "input_2", "input_3", "label_id", "label", "split"])
        w.writerows(all_rows)
    return all_rows


def export_header(model_bytes, path):
    lines = ["#pragma once", "// Generated by training/train.py; model float32.",
             "alignas(16) const unsigned char kSuitModel[] = {"]
    for i in range(0, len(model_bytes), 12):
        lines.append("  " + ", ".join(f"0x{v:02x}" for v in model_bytes[i:i+12]) + ",")
    lines += ["};", "const unsigned int kSuitModelLen = sizeof(kSuitModel);", ""]
    path.write_text("\n".join(lines), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", default=".")
    parser.add_argument("--epochs", type=int, default=180)
    args = parser.parse_args()
    if args.epochs < 1:
        parser.error("--epochs harus bernilai minimal 1")
    root = Path(args.out).resolve()
    for name in ["models", "wokwi", "reports"]:
        (root / name).mkdir(parents=True, exist_ok=True)
    tf.keras.utils.set_random_seed(SEED)
    rows = make_dataset(root)
    def split(name):
        selected = [r for r in rows if r[-1] == name]
        return (np.array([r[:3] for r in selected], dtype=np.float32) / 4095.0,
                np.array([r[3] for r in selected], dtype=np.int32))
    x_train, y_train = split("train")
    x_val, y_val = split("validation")
    x_test, y_test = split("test")

    model = tf.keras.Sequential([
        tf.keras.Input(shape=(3,), name="button_features"),
        tf.keras.layers.Dense(24, activation="relu"),
        tf.keras.layers.Dense(16, activation="relu"),
        tf.keras.layers.Dense(4, activation="softmax")
    ])
    model.compile(optimizer=tf.keras.optimizers.Adam(.003),
                  loss="sparse_categorical_crossentropy")
    # train_on_batch menghindari thread pool dataset pada runtime kecil.
    rng = np.random.default_rng(SEED + 1)
    best_loss = float("inf")
    best_weights = None
    history = []
    for epoch in range(args.epochs):
        order = rng.permutation(len(x_train))
        for start in range(0, len(order), 128):
            idx = order[start:start+128]
            model.train_on_batch(x_train[idx], y_train[idx])
        val_p = model(x_val, training=False).numpy()
        val_loss = float(-np.log(np.maximum(val_p[np.arange(len(y_val)), y_val], 1e-9)).mean())
        val_acc = float((val_p.argmax(1) == y_val).mean())
        history.append({"epoch": epoch + 1, "validation_loss": val_loss,
                        "validation_accuracy": val_acc})
        if val_loss < best_loss:
            best_loss, best_weights = val_loss, model.get_weights()
        if epoch == 0 or (epoch + 1) % 30 == 0:
            print(f"Epoch {epoch+1}: validation accuracy={val_acc:.3%}", flush=True)
    model.set_weights(best_weights)
    model.save(root / "models" / "suit.keras")

    # Bekukan bobot menjadi konstanta; menghindari resource-variable ops pada MCU.
    # Modul ini identik dengan Dense/ReLU/Softmax Keras di atas.
    class FrozenSuit(tf.Module):
        def __init__(self, weights):
            super().__init__()
            self.w = [tf.constant(w, dtype=tf.float32) for w in weights]

        @tf.function(input_signature=[tf.TensorSpec([1, 3], tf.float32, name="button_features")])
        def infer(self, x):
            x = tf.nn.relu(tf.matmul(x, self.w[0]) + self.w[1])
            x = tf.nn.relu(tf.matmul(x, self.w[2]) + self.w[3])
            return tf.nn.softmax(tf.matmul(x, self.w[4]) + self.w[5])

    frozen = FrozenSuit(model.get_weights())
    converter = tf.lite.TFLiteConverter.from_concrete_functions(
        [frozen.infer.get_concrete_function()], frozen)
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS]
    binary = converter.convert()
    (root / "models" / "suit_float32.tflite").write_bytes(binary)
    export_header(binary, root / "wokwi" / "model_data.h")
    interpreter = tf.lite.Interpreter(model_content=binary, num_threads=1)
    interpreter.allocate_tensors()
    inp = interpreter.get_input_details()[0]
    out = interpreter.get_output_details()[0]
    lite_probs = []
    for x in x_test:
        interpreter.set_tensor(inp["index"], x[None, :])
        interpreter.invoke()
        lite_probs.append(interpreter.get_tensor(out["index"])[0].copy())
    lite_probs = np.array(lite_probs)
    keras_probs = model(x_test, training=False).numpy()
    predictions = lite_probs.argmax(1)
    cm = np.zeros((4, 4), dtype=int)
    np.add.at(cm, (y_test, predictions), 1)
    accepted = (predictions != 3) & (lite_probs.max(1) >= .75)
    report = {
        "seed": SEED, "dataset": "synthetic button features; NOT real hand measurements",
        "tensorflow_version": tf.__version__, "keras_version": tf.keras.__version__,
        "normalization": "button feature encoding; input_1,input_2,input_3",
        "labels": LABELS, "architecture": [3, 24, 16, 4], "dtype": "float32",
        "samples": {"train": len(x_train), "validation": len(x_val), "test": len(x_test)},
        "tflite_bytes": len(binary), "sha256": hashlib.sha256(binary).hexdigest(),
        "test_accuracy": float((predictions == y_test).mean()),
        "confusion_matrix_rows_actual_columns_predicted": cm.tolist(),
        "per_class_recall": (np.diag(cm) / cm.sum(1)).tolist(),
        "max_abs_keras_tflite_error": float(np.max(np.abs(keras_probs - lite_probs))),
        "keras_tflite_class_agreement": float((keras_probs.argmax(1) == predictions).mean()),
        "accepted_samples_at_075": int(accepted.sum()),
        "accepted_accuracy_at_075": float((predictions[accepted] == y_test[accepted]).mean()) if accepted.any() else None,
        "ops": sorted(set(o["op_name"] for o in interpreter._get_ops_details()) - {"DELEGATE"}),
        "hardware_tested": False, "wokwi_simulation_tested": False
    }
    (root / "reports" / "training_metrics.json").write_text(
        json.dumps(report, indent=2), encoding="utf-8")
    (root / "reports" / "training_history.json").write_text(
        json.dumps(history, indent=2), encoding="utf-8")
    print(json.dumps(report, indent=2), flush=True)
    assert report["max_abs_keras_tflite_error"] < 1e-4
    assert set(report["ops"]) <= {"FULLY_CONNECTED", "SOFTMAX"}, report["ops"]
    print("Selesai. Gunakan wokwi/model_data.h bersama firmware.")


if __name__ == "__main__":
    main()
